# Generated by Django 4.2.16 on 2026-09-20 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_no', models.CharField(max_length=20, unique=True, verbose_name='案號')),
                ('welfare_no', models.CharField(blank=True, max_length=30, verbose_name='衛福案號')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('id_number', models.CharField(blank=True, max_length=10, verbose_name='身分證字號')),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女')], max_length=1, verbose_name='性別')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='電話')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='居住地址')),
                ('district', models.CharField(blank=True, max_length=50, verbose_name='居住區域')),
                ('city', models.CharField(blank=True, max_length=20, verbose_name='居住縣市')),
                ('cms_level', models.CharField(blank=True, choices=[('1', 'CMS 1級'), ('2', 'CMS 2級'), ('3', 'CMS 3級'), ('4', 'CMS 4級'), ('5', 'CMS 5級'), ('6', 'CMS 6級'), ('7', 'CMS 7級'), ('8', 'CMS 8級')], max_length=1, verbose_name='CMS等級')),
                ('status', models.CharField(choices=[('active', '服務中'), ('suspended', '暫停服務'), ('closed', '結案'), ('pending', '待開案')], default='pending', max_length=10, verbose_name='狀態')),
                ('service_start_date', models.DateField(blank=True, null=True, verbose_name='服務開始日期')),
                ('service_end_date', models.DateField(blank=True, null=True, verbose_name='服務結束日期')),
                ('source', models.CharField(blank=True, max_length=50, verbose_name='來源')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=50, verbose_name='緊急聯絡人')),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, verbose_name='緊急聯絡電話')),
                ('emergency_contact_relation', models.CharField(blank=True, max_length=20, verbose_name='關係')),
                ('notes', models.TextField(blank=True, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cases', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='accounts.organization', verbose_name='所屬機構')),
                ('primary_caregiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_cases', to=settings.AUTH_USER_MODEL, verbose_name='主責居服員')),
                ('sub_supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_supervised_cases', to=settings.AUTH_USER_MODEL, verbose_name='副督導')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_cases', to=settings.AUTH_USER_MODEL, verbose_name='督導')),
            ],
            options={
                'verbose_name': '個案',
                'verbose_name_plural': '個案管理',
                'ordering': ['-created_at'],
            },
        ),
    ]
