# Generated by Django 4.2.16 on 2026-09-21 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='geocode_source',
            field=models.CharField(blank=True, max_length=20, verbose_name='定位來源'),
        ),
        migrations.AddField(
            model_name='case',
            name='geocoded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='定位時間'),
        ),
        migrations.AddField(
            model_name='case',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='緯度'),
        ),
        migrations.AddField(
            model_name='case',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='經度'),
        ),
    ]
