# Generated by Django 4.2.16 on 2026-09-20 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='服務代碼')),
                ('name', models.CharField(max_length=100, verbose_name='服務名稱')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='類別')),
                ('unit', models.CharField(default='次', max_length=10, verbose_name='單位')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
            ],
            options={
                'verbose_name': '服務項目',
                'verbose_name_plural': '服務項目管理',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField(verbose_name='排定日期')),
                ('scheduled_start_time', models.TimeField(verbose_name='排定開始時間')),
                ('scheduled_end_time', models.TimeField(verbose_name='排定結束時間')),
                ('actual_start_time', models.DateTimeField(blank=True, null=True, verbose_name='實際開始時間')),
                ('actual_end_time', models.DateTimeField(blank=True, null=True, verbose_name='實際結束時間')),
                ('status', models.CharField(choices=[('pending', '待服務'), ('in_progress', '進行中'), ('completed', '已完成'), ('cancelled', '已取消'), ('abnormal', '異常')], default='pending', max_length=15, verbose_name='狀態')),
                ('service_notes', models.TextField(blank=True, verbose_name='服務紀錄')),
                ('client_signature', models.BooleanField(default=False, verbose_name='案家簽名確認')),
                ('quality_score', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='服務品質評分')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caregiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_records', to=settings.AUTH_USER_MODEL, verbose_name='居服員')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_records', to='cases.case', verbose_name='個案')),
                ('service_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.serviceitem', verbose_name='服務項目')),
            ],
            options={
                'verbose_name': '服務紀錄',
                'verbose_name_plural': '服務紀錄管理',
                'ordering': ['-scheduled_date', '-scheduled_start_time'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')], verbose_name='星期幾 (0=週一)')),
                ('start_time', models.TimeField(verbose_name='開始時間')),
                ('end_time', models.TimeField(verbose_name='結束時間')),
                ('effective_from', models.DateField(verbose_name='生效日期')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='結束日期')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
                ('caregiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to=settings.AUTH_USER_MODEL, verbose_name='居服員')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='cases.case', verbose_name='個案')),
                ('service_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.serviceitem', verbose_name='服務項目')),
            ],
            options={
                'verbose_name': '排班',
                'verbose_name_plural': '排班管理',
            },
        ),
    ]
