# Generated by Django 4.2.16 on 2026-09-21 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerecord',
            name='checkin_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='打卡緯度'),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='checkin_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='打卡經度'),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='checkout_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='簽退緯度'),
        ),
        migrations.AddField(
            model_name='servicerecord',
            name='checkout_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='簽退經度'),
        ),
    ]
