# Generated by Django 4.2.16 on 2026-09-20 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('fall', '跌倒/意外事件'), ('health', '身體狀況異常'), ('environment', '環境安全問題'), ('behavior', '情緒/行為異常'), ('complaint', '投訴/申訴'), ('caregiver', '居服員問題'), ('other', '其他')], max_length=20, verbose_name='事件類型')),
                ('severity', models.CharField(choices=[('low', '輕微'), ('medium', '中等'), ('high', '嚴重'), ('critical', '緊急')], default='low', max_length=10, verbose_name='嚴重程度')),
                ('status', models.CharField(choices=[('pending', '待處理'), ('processing', '處理中'), ('resolved', '已結案'), ('tracking', '追蹤中')], default='pending', max_length=15, verbose_name='狀態')),
                ('occurred_at', models.DateTimeField(verbose_name='發生時間')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='發生地點')),
                ('description', models.TextField(verbose_name='事件描述')),
                ('immediate_action', models.TextField(blank=True, verbose_name='立即處理措施')),
                ('follow_up_notes', models.TextField(blank=True, verbose_name='追蹤紀錄')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='結案時間')),
                ('resolution_summary', models.TextField(blank=True, verbose_name='處理結果摘要')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL, verbose_name='負責處理人員')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='cases.case', verbose_name='個案')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_incidents', to=settings.AUTH_USER_MODEL, verbose_name='回報人員')),
            ],
            options={
                'verbose_name': '異常事件',
                'verbose_name_plural': '異常事件管理',
                'ordering': ['-occurred_at'],
            },
        ),
    ]
