# Generated by Django 4.2.16 on 2026-09-21 03:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_service_site',
            field=models.BooleanField(default=True, verbose_name='為服務據點'),
        ),
        migrations.AddField(
            model_name='organization',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='緯度'),
        ),
        migrations.AddField(
            model_name='organization',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='經度'),
        ),
        migrations.AddField(
            model_name='user',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_staff', to=settings.AUTH_USER_MODEL, verbose_name='所屬督導'),
        ),
    ]
