# Generated by Django 4.2.16 on 2026-09-21 03:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaregiverLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='緯度')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='經度')),
                ('accuracy_m', models.FloatField(blank=True, null=True, verbose_name='定位誤差(公尺)')),
                ('source', models.CharField(choices=[('mobile', '手機回報'), ('checkin', '服務打卡'), ('manual', '人工設定'), ('mock', '模擬資料')], default='mobile', max_length=10, verbose_name='來源')),
                ('recorded_at', models.DateTimeField(db_index=True, verbose_name='回報時間')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('caregiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to=settings.AUTH_USER_MODEL, verbose_name='居服員')),
            ],
            options={
                'verbose_name': '居服員位置',
                'verbose_name_plural': '居服員位置紀錄',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['caregiver', '-recorded_at'], name='geo_caregiv_caregiv_9f1ee9_idx')],
            },
        ),
    ]
